# Generated by Django 4.2.4 on 2023-09-20 01:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEsp', models.CharField(max_length=10, unique=True)),
                ('nombreEsp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasMedicas.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoMedico', models.CharField(max_length=10, unique=True)),
                ('nombreMedico', models.CharField(max_length=100)),
                ('especialidades', models.ManyToManyField(through='CitasMedicas.EspecialidadMedico', to='CitasMedicas.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='especialidadmedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasMedicas.medico'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('vigencia', models.BooleanField(default=True)),
                ('diacita', models.DateField(default=datetime.date.today)),
                ('horacita', models.TimeField()),
                ('mensaje', models.TextField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasMedicas.paciente')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasMedicas.medico')),
            ],
        ),
    ]
